### ISSUE TITLE
Formatter for generated IPS code

### ISSUE THREAD

**Issue by belaso** [faktorips/faktorips.base#1]
Hello faktorips developers,

is it possible in faktorips to generate the java code formatted with Eclipse standard code formatter? My issue is: I want to edit "@generated NOT" methods in generated classes and format my code with Eclipse formatter. If I do so, I get a differences also in generated methods because the generated code is not formatted with Eclipse standard formatter.

Regards Christian

**Comment by cdir** [comment]
Hi Christian,

what kind of changes do you have in edited code? Faktor-IPS does already use the configured eclipse code formatter to format all generated code. But sometimes the project settings are inconsistent regarding code formatter rules and save actions. Eclipse has a lot of save actions that are not directly reflected by the code formatter rules. For example rules for whitespaces especially in java doc comments. There might be a save action to remove these white spaces but a code formatter rule that adds a space in every blank line. Then it depends on what comes first.

Faktor-IPS could only run code formatter not the save actions. That's because save actions are part of the eclipse UI and only code formatter is available in jdt core.

If you have some detailed example I might help with finding the correct settings.

Kindly, Cornelius

**Comment by belaso** [comment]
Hi @cdir,

thanks for your very quick response :+1: and for the tip with save actions. Our problem was the following Save Action

![screen1](https://user-images.githubusercontent.com/1709299/47483203-f67dae00-d838-11e8-8368-39ae4b5fe78b.png)

I simply disabled this (not necessary) save action and the problem is gone :-)

Christian
